# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_home": "00_core.ipynb",
         "HOME": "00_core.ipynb",
         "dump_pickle": "00_core.ipynb",
         "load_pickle": "00_core.ipynb",
         "add_time_stamp": "00_core.ipynb",
         "L_ROOT": "00_core.ipynb",
         "D_ROOT": "00_core.ipynb",
         "DBS_REL": "00_core.ipynb",
         "DBS": "00_core.ipynb",
         "ZAPPOS_META_DIR": "00_core.ipynb",
         "SCRAPED_META_DIR": "00_core.ipynb",
         "IMG_SIZE_LG": "00_core.ipynb",
         "IMG_SIZE_MD": "00_core.ipynb",
         "IMG_SIZE_SM": "00_core.ipynb",
         "IMG_SIZE": "00_core.ipynb",
         "IMG_SIZES": "00_core.ipynb",
         "IMSZ2LAB": "00_core.ipynb",
         "SIZE_ABBR": "00_core.ipynb",
         "ZAPPOS_DF_SIMPLIFIED": "00_core.ipynb",
         "ZAPPOS_FEATS_ALL": "00_core.ipynb",
         "ZAPPOS_FEATS_ALL_SORT": "00_core.ipynb",
         "ZAPPOS_FEATS_SM": "00_core.ipynb",
         "ZAPPOS_FEATS_MD": "00_core.ipynb",
         "ZAPPOS_FEATS_LG": "00_core.ipynb",
         "SCRAPED_DF": "00_core.ipynb",
         "COMBINED_DF": "00_core.ipynb",
         "QUERY_IM": "00_core.ipynb",
         "QUERY_IM2": "00_core.ipynb",
         "BETA": "00_core.ipynb",
         "LATENT_DIM": "00_core.ipynb",
         "mobilenet_v2_meta": "00_core.ipynb",
         "get_zappos_db": "01a_data.munge.ipynb",
         "read_zappos_meta": "01a_data.munge.ipynb",
         "simplify_zappos_db": "01a_data.munge.ipynb",
         "skl_tt_split": "01a_data.munge.ipynb",
         "extract_cat": "01a_data.munge.ipynb",
         "extract_brand_goat": "01a_data.munge.ipynb",
         "extract_brand_sns": "01a_data.munge.ipynb",
         "extract_db_nm": "01a_data.munge.ipynb",
         "get_scraped_db": "01a_data.munge.ipynb",
         "merge_dbs": "01a_data.munge.ipynb",
         "extract_zap_sneakers": "01a_data.munge.ipynb",
         "add_subdir": "01b_data.load.ipynb",
         "creat_full_local_categorydirs": "01b_data.load.ipynb",
         "create_test_train_directories": "01b_data.load.ipynb"}

modules = ["core.py",
           "data/munge.py",
           "data/load.py"]

doc_url = "https://ergonyc.github.io/snkrfinder/"

git_url = "https://github.com/ergonyc/snkrfinder/tree/master/"

def custom_doc_links(name): return None
